### ISSUE TITLE
Misleading names

### ISSUE THREAD

**Issue by Velua** [eoscafe/eos-airdrops#209]
https://github.com/eoscafe/eos-airdrops/blob/1588f78407390f0cb29be61683090c44973b8645/tokens.json#L1488-L1503

While we cannot stop anyone from deciding whatever their token symbol is going to be I feel like it's a bit misleading having a name of BTC or ETH, where it's really Newdex BTC or Newdex ETH. 

Thoughts on changing? 

```     "name": "Newdex BTC", ```

**Comment by DenisCarriere** [comment]
Makes sense

**Comment by Tomi1883** [comment]
> https://github.com/eoscafe/eos-airdrops/blob/1588f78407390f0cb29be61683090c44973b8645/tokens.json#L1488-L1503
> 
> While we cannot stop anyone from deciding whatever their token symbol is going to be I feel like it's a bit misleading having a name of BTC or ETH, where it's really Newdex BTC or Newdex ETH.
> 
> Thoughts on changing?
> 
> ` "name": "Newdex BTC",`
