### ISSUE TITLE
Agregar logos por favor

### ISSUE THREAD

**Issue by karedgold** [eoscafe/eos-airdrops#329]
Hola
Necesito que se agreguen los logos de mis tokens
GUSI: XGUS
G-GUX: GUX
KSK PLUS: KSK
a cntinuación envio los logos correspondientes
![gusi](https://user-images.githubusercontent.com/30392568/114949284-afc40a00-9e1e-11eb-81c2-d2e55e2a9a59.png)
![G-GUX](https://user-images.githubusercontent.com/30392568/114949281-af2b7380-9e1e-11eb-818e-6601f7f17f9c.png)
![KSK +](https://user-images.githubusercontent.com/30392568/114949285-b05ca080-9e1e-11eb-82a4-bf712fb15204.png)

**Comment by DenisCarriere** [comment]
Please provide a Pull Request with your following token request
