### ISSUE TITLE
Missing logo files

### ISSUE THREAD

**Issue by includenull** [eoscafe/eos-airdrops#620]
The following logo files are missing:
```
ihooeostoken-hoo.jpg
viitasphere.png
viitasphere-lg.png
viitasphere.png
viitasphere-lg.png
telosdac.png
telosdac-lg.png
BTCPtelosPurple1.png
ppnx.png
ppnx-lg.png
CHIA-wax-seeds.pet.png
````

I couldn't find appropriate images to add to fix these nor could I find the original commits that added some of these.

`eosCASH` also doesn't have any logos set.

`eosreeltoken` has a dead URL too.

Should these just be left in there or removed?

**Comment by DenisCarriere** [comment]
👍  cleaned up those files

Added tests so next PR would catch those errors:
https://github.com/eoscafe/eos-airdrops/blob/master/tokens.spec.ts
