### ISSUE TITLE
We want to add WAL into your token list 

### ISSUE THREAD

**Issue by Nidaxiangge** [eoscafe/eos-airdrops#96]
Hi there
   Here is the BD of WhaleEx, we'd like to add WAL into your token list.
   https://eosflare.io/token/whaleextoken/WAL

**Comment by NatPDeveloper** [comment]
You can create a pull request by first forking the repository, committing changes to forked master, then submitting a PR from the fork's master. 

Like this:

```sh
eoscafe:master from NatPDeveloper:master
```

To Add:
- token / contract to README.md
- info to tokens.json
- logos to /logos 
  - logo.png (128x128 pixels)
  - logo-lg.png (400x400 pixels)
